# Nome do workdlow
name: ci-golank-workflow

# O processo irá inciar toda vez que acontecer um PR no branch develop
on: 
  pull_request:
    branches:
      - develop

# Jobs seria o agrupamentos de processos
jobs:
  # Um processo
  check-application:
    # Será realizado em um imagem ubuntu
    runs-on: ubuntu-latest
    # Utilizando a estratégia matrix é possivel testar em outras versões
    # strategy:
      # matrix:
        # go: ['1.14', '1.15']
    steps:
      # Pega os dados que acabam de ser feito push e baixar na máquina
      - uses: actions/checkout@v2
      # Prepara a máquina com um setup para rodar golang
      - uses: actions/setup-go@v2
        with:
          # Selecionando as versões do golang pelo matrix
          # go-version: ${{ matrix.go }}
          go-version: 1.15
      - run: go test
      - run: go run math.go
    
      # Passos para executar o docker e fazer push no dockerhub
        # Prepara o ambiente para executar o docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # Prepara o ambiente para buildar o docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Faz o login no dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Faz o build da imagem do dockerfile
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # Difine se será feito o push no dockerhub
          push: true
          tags: gabrielprogramerdocker/go-project-ci:latest