# Nome do workdlow
name: ci-golank-workflow

# O processo irá inciar toda vez que acontecer um PR no branch develop
on: 
  pull_request:
    branches:
      - develop

# Jobs seria o agrupamentos de processos
jobs:
  # Um processo
  check-application:
    # Será realizado em um imagem ubuntu
    runs-on: ubuntu-latest
    # Utilizando a estratégia matrix é possivel testar em outras versões
    strategy:
      matrix:
        go: ['1.14', '1.15']
    steps:
      # Pega os dados que acabam de ser feito push e baixar na máquina
      - uses: actions/checkout@v2
      # Prepara a máquina com um setup para rodar golang
      - uses: actions/setup-go@v2
        with:
          # Selecionando as versões do golang pelo matrix
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go